### ISSUE TITLE
Grayscale resmi 8, 16 ve 24 bit'e dönüştürme.

### ISSUE THREAD

**Issue by ademclk** [mesutpiskin/opencv-tutorial#12]
Python ve opencv kullanarak bunu yapmaya çalışıyorum fakat nasıl yapacağımı anlayamadım.

Bunun kolay ve hızlı yolunun, resmin gri yoğunluğunun alınıp rgb'ye çevirilmesi olarak yazılmış. Fakat bunu 8 16 24 bit'e nasıl çevirebilirim. Yardımcı olursanız sevinirim.

**Comment by mustafakoca99** [comment]
Merhaba,
CvtColor alanında ki color yerine;

COLOR_RGB2BGR
COLOR_RGB2BGRA
COLOR_RGB2GRAY
COLOR_GRAY2RGB
COLOR_RGB2HLS
COLOR_HSV2RGB
COLOR_RGB2HSV
COLOR_RGB2Luv
COLOR_HSV2RGB
COLOR_RGB2YUV
COLOR_RGB2Lab

Bunlardan birisini yaz ve dene, ben daha önce renkli version kullanmadım.

**Comment by ademclk** [comment]
Merhaba, durumu bit düzlemi dilimleme çözdüm yapmak istediğim renkli olması değilmiş. Teşekkürler.
